### ISSUE TITLE
Laravel 7 integration hangs when adding the package

### ISSUE THREAD

**Issue by petericebear** [kodekeep/laravel-paddle#3]
With a Laravel 7 app I try to add the package with:
composer require kodekeep/laravel-paddle

Then I get this error:
![image](https://user-images.githubusercontent.com/339796/81566023-8bec7e80-939a-11ea-9d5b-4e473a54c9eb.png)

I think the dependency needs to be updated of the sdk. Can you add that and trigger a new version?

**Comment by faustbrian** [comment]
Odd, I have it running in production with 2 applications on Laravel 7.

The `paddle-sdk` package supports Laravel 7 since 1.1.0 https://github.com/kodekeep/paddle-sdk/compare/1.0.0...1.1.0

**Comment by petericebear** [comment]
ah it has todo with KiteTail. When I install that it give the same error
![image](https://user-images.githubusercontent.com/339796/81566648-7592f280-939b-11ea-9bc9-e44152a9e756.png)

**Comment by faustbrian** [comment]
If you are on Laravel 7 you don't need `Zttp` but can use https://laravel.com/docs/7.x/http-client instead which is based on `Zttp`.

**Comment by petericebear** [comment]
I reverted to a couple of commits back (used laravel shift for the upgrade of the old app).

And before I ran composer update, I installed this package. Which kept tightenco/collect to a lower version. I have it installed now. But kitetail which needed from the sdk dependencies triggered the error somewhere along the way.

**Comment by faustbrian** [comment]
Oh sorry I misunderstood the `Zttp` issue. I'll upgrade the SDK to use the `illuminate/http` package instead.

**Comment by faustbrian** [comment]
@petericebear could you test https://github.com/kodekeep/laravel-paddle/releases/tag/1.3.0 and let me know if you encounter any issues? It now uses `kodekeep/paddle-sdk:1.2.0` which uses `illuminate/http` instead of `kitetail/zttp`.

**Comment by petericebear** [comment]
This worked
![image](https://user-images.githubusercontent.com/339796/81569727-f18f3980-939f-11ea-925e-72c8e4312b9e.png)

**Comment by faustbrian** [comment]
Great, let me know if you run into issues with the new `illuminate/http` usage. Things like failing requests or wrong results.

**Comment by petericebear** [comment]
>>> dd(Paddle::subscription()->plans()->all());
KodeKeep/Paddle/Exceptions/RequestException with message 'Received unexpected response with status code 200.'
I am trying through tinker and get this error. There are plans in Paddle available.

**Comment by petericebear** [comment]
And through tinkerwell I get this response:

![image](https://user-images.githubusercontent.com/339796/81572054-04efd400-93a3-11ea-9ee1-df9a65da8c30.png)

**Comment by faustbrian** [comment]
> ```
> dd(Paddle::subscription()->plans()->all());
> ```
> 
> KodeKeep/Paddle/Exceptions/RequestException with message 'Received unexpected response with status code 200.'
> I am trying through tinker and get this error. There are plans in Paddle available.

https://github.com/kodekeep/paddle-sdk/releases/tag/1.2.1

**Comment by faustbrian** [comment]
> And through tinkerwell I get this response:
> 
> ![image](https://user-images.githubusercontent.com/339796/81572054-04efd400-93a3-11ea-9ee1-df9a65da8c30.png)

That looks like a syntax error if you are not on PHP 7.4

**Comment by petericebear** [comment]
I am on PHP 7.4.1
![image](https://user-images.githubusercontent.com/339796/81573092-551b6600-93a4-11ea-86b9-b7488990b83e.png)

**Comment by petericebear** [comment]
OpCache is disabled

**Comment by faustbrian** [comment]
Are your php-fpm and php-cli both on PHP 7.4? Your php-fpm doesn't seem to have issues with executing the code but your CLI does.

**Comment by petericebear** [comment]
Ah in tinkwell there was a link to 7.3.1. After that and updating the version for the SDK I now get the responses :D
