### ISSUE TITLE
When cancelling a subscription

### ISSUE THREAD

**Issue by petericebear** [kodekeep/laravel-paddle#5]
Hi,

I saw this listener and when someone is cancelling the subscription the plan_id is also removed from the model, in this case the subscription and plan is removed and you will only have the on_grace_period date but the plan is removed.

Maybe it is better to only set the grace_period_ends_at with a value?
Then all the other information can be left, and after the grace_period_ends_at date with a command remove those lines to null just like the clear due trials command.

https://github.com/kodekeep/laravel-paddle/blob/7b1c15d53a2811d23ae403f71198a065e9d4136a/src/Billing/Listeners/DeleteSubscriptionInformation.php#L29-L30

Just ventilating here about the possibilties.

Greetings

**Comment by petericebear** [comment]
The subscription still remains on the user in Paddle, but gets the status "deleted".

**Comment by faustbrian** [comment]
Would that work as you expect @petericebear https://github.com/kodekeep/laravel-paddle/pull/6?

**Comment by petericebear** [comment]
I think it must be a new command instead of adjusting the current clearing of the trial, but the Webhook yeah those changes are good.

**Comment by petericebear** [comment]
And with that new command:
ClearCancelledSubscriptionsCommand

$team->forceFill([
                    'paddle_subscription_id'      => null,
                    'paddle_subscription_plan_id' => null,
                    'grace_period_ends_at'               => null,
                ])->save();

Based on the PaddleID the old invoices can still be obtained.

**Comment by faustbrian** [comment]
Pushed some changes that should cover the past due scenarios of trials and grace periods.

**Comment by petericebear** [comment]
You are fast! I think these changes are great for all the use cases now.

**Comment by faustbrian** [comment]
Should be on packagist in a few minutes https://github.com/kodekeep/laravel-paddle/releases/tag/1.4.0
